# Generated by Django 4.1.5 on 2023-01-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('url_image', models.URLField()),
                ('news_source', models.CharField(max_length=100)),
                ('source', models.URLField()),
                ('news_author', models.CharField(max_length=100)),
                ('is_top_in_category', models.BooleanField(default=False)),
                ('is_top_news', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=10)),
                ('requests_nb', models.IntegerField()),
                ('dataPath_map', models.CharField(max_length=20)),
                ('title_map', models.CharField(max_length=20)),
                ('subTitle_map', models.CharField(max_length=20)),
                ('content_map', models.CharField(max_length=20)),
                ('imageUrl_map', models.CharField(max_length=20)),
                ('provider_map', models.CharField(max_length=20)),
                ('publishedAt_map', models.CharField(max_length=20)),
                ('source_map', models.CharField(max_length=20)),
                ('category_map', models.CharField(max_length=20)),
                ('author_map', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.provider'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField()),
                ('footer_title', models.CharField(max_length=50)),
                ('footer_description', models.CharField(max_length=150)),
                ('instagram_url', models.URLField(default=None)),
                ('facebook_url', models.URLField(default=None)),
                ('twitter_url', models.URLField(default=None)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category1', to='news.category')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category2', to='news.category')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category3', to='news.category')),
                ('category4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category4', to='news.category')),
                ('category5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category5', to='news.category')),
                ('category6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category6', to='news.category')),
            ],
        ),
    ]
