# Generated by Django 4.1.5 on 2023-01-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_provider_host_alter_provider_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name_plural': 'CMS'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='readlater',
            options={'verbose_name_plural': 'Read Later'},
        ),
    ]
