# Generated by Django 4.1.5 on 2023-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options_alter_cms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
