# Generated by Django 4.1.5 on 2023-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
