# Generated by Django 4.1.5 on 2023-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_title_alter_subscription_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.AddField(
            model_name='like',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
