# Generated by Django 4.1.5 on 2023-01-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_newssource_remove_category_title_remove_provider_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.AddField(
            model_name='provider',
            name='dashboard',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
